services:
  api:
    image: ghcr.io/flipdot/snatch-backend
    volumes:
      - .:/code
    environment:
      - REDIS_URL=redis://db:6379/0
    depends_on:
      - db
  frontend:
    image: ghcr.io/flipdot/snatch-frontend
    depends_on:
      - api
  db:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  caddy:
    image: caddy:2.6.4-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./infrastructure/Caddyfile:/etc/caddy/Caddyfile"
      - "caddy-data:/data"
      - "static_files:/mnt/static"
#      - "media_files:/mnt/media"
    depends_on:
      - api
      - frontend
volumes:
  redis-data:
  caddy-data:
  static_files:
#  media_files:
