services:
  api:
    build:
      context: ./backend
    volumes:
      - .:/code
    environment:
      - REDIS_HOST=db
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    depends_on:
      - api
  db:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  redis-data:
  static_files:
#  media_files:
