services:
  api:
    build:
      context: ./backend
    image: ghcr.io/flipdot/snatch-backend
    volumes:
      - .:/code
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - REDIS_HOST=db
      # required to make SSL redirection work. IMHO not worth figuring out the real IP: https://stackoverflow.com/a/69369838/458274
      - FORWARDED_ALLOW_IPS=*
    depends_on:
      - db
  frontend:
    image: ghcr.io/flipdot/snatch-frontend
    depends_on:
      - api
  db:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  caddy:
    image: caddy:2.7.6-alpine
    ports:
      - "8000:8000"
#      - "443:443"
    volumes:
      - "./infrastructure/Caddyfile:/etc/caddy/Caddyfile"
      - "caddy-data:/data"
      - "static_files:/mnt/static"
#      - "media_files:/mnt/media"
    depends_on:
      - api
      - frontend
volumes:
  redis-data:
  caddy-data:
  static_files:
#  media_files:
